### ISSUE TITLE
Store used URL to verify objects

### ISSUE THREAD

**Issue by Jan200101** [int-72h/toast#19]
OFLauncher-rei supports specifying a server to download the files from, which can have different revisions than the official `toast.openfortress.fun`.

If a user, for whatever reason, decides to change the URL *after* installing this can lead to files being left in the incorrect state.

To fix this I propose adding a `.remote` (or similar #18) that lets the program verify what remote was used last and if we need to verify the files from the first revision onwards

**Comment by w3bb** [comment]
This doesn't solve the problem. All it would do is basically just replay from revision zero, which in turn is effectively a reinstall with checks for the current overlapping files. I think a better solution is to include a unique name for the thing that is installed. This would prevent disasterous situations, but also gives us an opportunity to warn the user. Think something like a file called .product with the contents "openfortress/openfortress",

**Comment by Jan200101** [comment]
> This doesn't solve the problem. All it would do is basically just replay from revision zero, which in turn is effectively a reinstall with checks for the current overlapping files.

That is the point.
There is no simple way, without storing things client side, of ensuring that the new server and old server provide the same info without sending a bunch of queries to both.
With the current architecture its easier to simply fetch all file changes from 0 to LATEST and verify if they are locally present.

> I think a better solution is to include a unique name for the thing that is installed. This would prevent disasterous situations, but also gives us an opportunity to warn the user. Think something like a file called .product with the contents "openfortress/openfortress",

a simple name would hold no authority over the state of the revisions, any repo could copy an existing product name while being incompatible.
One way to establish authority would be having each revision contain a hash of all files combined together from rev 0 to the CURRENT REVISON, allowing a client to verify that the revision we are on is indeed the same one as on the server without having to do a bunch of checking.

But since the current data the revision endpoint returns is an array of file metadata, we can't simply add this kind of revision information without breaking backwards compatibility, thus the only kind of authority we can derive, without being backwards incompatible and while holding as much authority as we can, is by checking if we changed servers or not

**Comment by w3bb** [comment]
> There is no simple way, without storing things client side, of ensuring that the new server and old server provide the same info without sending a bunch of queries to both.
> a simple name would hold no authority over the state of the revisions, any repo could copy an existing product name while being incompatible.

TVN was designed to work with a trusted host. This is why we use MD5, it's only for incidential damage. What I'm proposing is also for incidential damage. It's meant for users accidentially choosing some other game.

**Comment by Jan200101** [comment]
> > There is no simple way, without storing things client side, of ensuring that the new server and old server provide the same info without sending a bunch of queries to both.
> > a simple name would hold no authority over the state of the revisions, any repo could copy an existing product name while being incompatible.
> 
> TVN was designed to work with a trusted host. This is why we use MD5, it's only for incidential damage. What I'm proposing is also for incidential damage. It's meant for users accidentially choosing some other game.

How can you trust that the server that says its `openfortress` is truly openfortress?

That is why I suggest using the host, or rather just the full domain + path so that changes between http and https won't break things since that is the authorative name that we use to connect to what we presume to be a known good server in regards to our local state.

**Comment by w3bb** [comment]
> How can you trust that the server that says its openfortress is truly openfortress?
HTTPS.

**Comment by Jan200101** [comment]
> > How can you trust that the server that says its openfortress is truly openfortress?
> 
> HTTPS.

that is not an answer
HTTPS ensures that the traffic is secure, not that tis server is in the same state as another.

toast.openfortress.fun can say its `openfortress`, but so can mirror.blab.ru

**Comment by w3bb** [comment]
As I've mentioned TVS was designed such that you are supposed to be able to trust the server you're downloading from. If there's nothing else to add I'll be closing this issue.

**Comment by Jan200101** [comment]
> As I've mentioned TVS was designed such that you are supposed to be able to trust the server you're downloading from. If there's nothing else to add I'll be closing this issue. If we need to change our threat model that's for another issue.

Yes and that is fine
but one thing you really should not trust a server on is if it matches another servers revision state.

Lets give an example for this:
`of-fix.mirror.ex` points to a custom tvn repo with a modified client libary that adds some nice features a few people had asked for otherwise its 1:1 the same as `toast.openfortress.fun`.

If a user went and changed the URL in oflauncher-rei it would check if `.revisions` is lower and if so update to that newest version.
Otherwise it goes and does nothing.

Now, if the user does while they are on the latest version they do not receive the changed files and are required to manually intervene by deleting `.revision` and thus forcing the launcher to recheck every file.

---

The user and client *trust* both servers just fine but there is no way of migrating to a new server without having to manually intervene
